services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WEATHER_API_KEY: ${WEATHER_API_KEY}
        WEATHER_API_URL: ${WEATHER_API_URL}
    restart: always
    ports:
      - 3000:3000
